# fly.toml app configuration file generated for email-service-v2
app = 'email-service-v2'
primary_region = 'sin'  # Singapore region, you can change this to your preferred region

[build]

[env]
  PORT = '4000'
  NODE_ENV = 'production'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api"

[vm]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[vm.mounts]]
  source = 'email_service_data'
  destination = '/data'

[deploy]
  strategy = 'rolling'

# Optional: Add secrets for environment variables
# You can set these using: flyctl secrets set VARIABLE_NAME=value
# Common secrets for email service:
# - SMTP_HOST
# - SMTP_PORT  
# - SMTP_USER
# - SMTP_PASS
# - EMAIL_FROM
